# Generated by Django 3.2 on 2023-03-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Painting', 'verbose_name_plural': 'Paintings'},
        ),
    ]
