# Generated by Django 6.0.5 on 2026-05-13 18:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='inspiration_ru',
            field=models.TextField(blank=True, help_text='Русская версия вдохновения', verbose_name='Вдохновение (RU)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='inspiration',
            field=models.TextField(blank=True, help_text='Short emotional story or inspiration', verbose_name='Inspiration'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
