# Generated by Django 6.0.5 on 2026-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_content_ru_gallery_inspiration_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='price',
            new_name='price_eur',
        ),
        migrations.AddField(
            model_name='gallery',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
